[package]
name = "tq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
json = "0.12"
regex = "1.5"
lazy_static = "1.4"
tempdir = "0.3"
